#!/usr/bin/env bash
# oracle-build.sh — Generate DEVBOY's CLAUDE.md from sources, with auto-backup.
#
# Pattern borrowed from Wind's doctor-oracle (2026-05-12 scout, vibe-hub-co/doctor-oracle).
# Why: deterministic generation eliminates hand-edit drift; timestamped backups
# preserve identity history out-of-band (git captures commits, backups capture
# every regeneration — the state actually live during a session).
#
# Usage:
#   ./scripts/oracle-build.sh           # generate CLAUDE.md, backup previous
#   ./scripts/oracle-build.sh --check   # generate to temp, diff vs current, no write
#
# Inputs:
#   oracle-build/shared-claude.md       — fleet-wide rules (universal doctrine)
#   oracle-build/oracle-devboy-claude.md — DEVBOY identity (orchestrator)
#
# Outputs:
#   CLAUDE.md                            — generated, committed (orchestrator)
#   .oracle-build-backups/*.YYYYMMDD-HHMMSS — local-only forensic copies
#
# Note: AGENTS.md is HAND-MAINTAINED (Codex worker contract — different audience
# from CLAUDE.md). It is NOT regenerated by this script. Pattern adopted from
# Wind's doctor-oracle (2026-05-24 doctrine sync). To update AGENTS.md, edit it
# directly.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

BUILD_DIR="oracle-build"
SHARED="$BUILD_DIR/shared-claude.md"
IDENTITY="$BUILD_DIR/oracle-devboy-claude.md"
OUTPUTS=("CLAUDE.md")
BACKUP_DIR=".oracle-build-backups"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

# Sanity: sources must exist
for f in "$SHARED" "$IDENTITY"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: missing source: $f" >&2
    exit 1
  fi
done

# Generate to temp first
TMP_OUT="$(mktemp)"
trap 'rm -f "$TMP_OUT"' EXIT

{
  cat "$IDENTITY"
  # If shared-claude.md has real content (non-comment lines), append with separator
  if grep -qv '^[[:space:]]*\(<!--\|-->\|$\)' "$SHARED" 2>/dev/null; then
    echo ""
    echo "<!-- ===== shared-claude.md ===== -->"
    echo ""
    cat "$SHARED"
  fi
} > "$TMP_OUT"

# --check mode: diff only, no write
if [ "${1:-}" = "--check" ]; then
  STATUS=0
  for output in "${OUTPUTS[@]}"; do
    if [ -f "$output" ] && diff -q "$output" "$TMP_OUT" >/dev/null 2>&1; then
      echo "✓ $output is in sync with sources"
    else
      echo "✗ $output differs from generated output:"
      diff "$output" "$TMP_OUT" || true
      STATUS=1
    fi
  done
  exit "$STATUS"
fi

mkdir -p "$BACKUP_DIR"
for output in "${OUTPUTS[@]}"; do
  tmp_each="$(mktemp)"
  cp "$TMP_OUT" "$tmp_each"

  if [ -f "$output" ]; then
    cp "$output" "$BACKUP_DIR/$output.$TIMESTAMP"
    backup_line="backup: $BACKUP_DIR/$output.$TIMESTAMP"
  else
    backup_line="no previous $output to backup"
  fi

  mv "$tmp_each" "$output"
  lines=$(wc -l < "$output" | tr -d ' ')
  bytes=$(wc -c < "$output" | tr -d ' ')
  echo "✓ generated $output ($lines lines, $bytes bytes)"
  echo "  $backup_line"
done

trap - EXIT
rm -f "$TMP_OUT"
echo "  sources: $IDENTITY + $SHARED"
